#!/usr/bin/env python3
"""Emit a SQL query that finds already-drafted picks whose stored position no
longer matches the current players.json (e.g. after a squad-list correction).

The draft stores each pick's position/slot as a snapshot at draft time, so a
later position fix in players.json doesn't rewrite existing picks. Scoring is
always computed from the live position, so this is a roster-tidiness check —
it lists picks you may want to re-slot, with the manager, drafted vs correct
position, and the slot/is_sub needed to rebuild the slot.

Usage:
  python check_picks.py                         # scan every league
  python check_picks.py --league "My League"    # one league
  python check_picks.py --league "My League" > check.sql

Paste the output into the Supabase SQL Editor (read-only; it only selects).
"""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).parent


def sql_str(s: str) -> str:
    """Single-quote a value for SQL, doubling embedded quotes."""
    return "'" + s.replace("'", "''") + "'"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--league", help="Restrict to this league name (exact).")
    args = ap.parse_args()

    players = json.loads((ROOT / "players.json").read_text(encoding="utf-8"))
    rows = ",\n".join(
        f"  ({sql_str(p['player_id'])},{sql_str(p['position'])})" for p in players
    )

    where_league = (f"  and l.name = {sql_str(args.league)}\n"
                    if args.league else
                    "  -- and l.name = 'Your League Name'   -- uncomment to filter\n")

    print(f"""\
-- Already-picked players whose drafted position != current players.json.
-- Read-only. Generated by check_picks.py from {len(players)} players.
with truth(player_id, correct_position) as (values
{rows}
)
select l.name as league, m.name as manager, p.player_name, p.player_id,
       p.position as drafted_position, t.correct_position, p.slot, p.is_sub
from picks p
join leagues l on l.id = p.league_id
join truth t on t.player_id = p.player_id
left join managers m on m.id = p.manager_id
where p.position is distinct from t.correct_position
{where_league}order by l.name, m.name, p.player_name;""")


if __name__ == "__main__":
    main()
